import { Canvas } from "@react-three/fiber";
import { Suspense } from "react";
import Loader from "../components/Home/Loader";
import Book from "../models/Book";
import Sky from "../models/Sky";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pixel (https://sketchfab.com/stefan.lengyel1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-fantasy-book-06d5a80a04fc4c5ab552759e9a97d91a
Title: Medieval Fantasy Book
*/

const Home = () => {
  const adjustBookForScreenSize = () => {
    let screenScale = null;
    let screenPosition = [0, 5, -25];
    let rotation = [0.6, 4.7, 0.05];

    if (window.innerWidth < 768) {
      screenScale = [0.2, 0.2, 0.2];
    } else {
      screenScale = [0.4, 0.4, 0.4];
    }

    return [screenScale, screenPosition, rotation];
  };

  const [bookScale, bookPosition, bookRotation] = adjustBookForScreenSize();

  return (
    <section className="w-full h-screen relative">
      <div className="absolute top-28 left-0 right-0 bottom-0 z-10 flex items-center justify-center">
        <Canvas
          className="w-full h-screen bg-transparent"
          camera={{ near: 0.1, far: 1000 }}
        >
          <Suspense fallback={<Loader />}>
            <directionalLight position={[1, 1, 1]} intensity={2} />
            <ambientLight intensity={0.5} />
            <hemisphereLight
              skyColor={"#b1e1ff"}
              groundColor={"#000000"}
              intensity={1}
            />
            <Sky />
            <Book
              scale={bookScale}
              position={bookPosition}
              rotation={bookRotation}
            />
          </Suspense>
        </Canvas>
      </div>
    </section>
  );
};

export default Home;
